"""add settings to users

Revision ID: c9603eb21d50
Revises: a1b2c3d4e5f6
Create Date: 2026-04-13 15:21:52.364334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9603eb21d50'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # Criar enums primeiro
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE review_status_enum AS ENUM ('approved', 'pending', 'rejected');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE question_type_enum AS ENUM ('interpretacao', 'aplicacao', 'raciocinio', 'memorizacao');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alternatives', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('alternatives_question_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materials', sa.JSON(), nullable=False))
        batch_op.drop_column('material_url')

    with op.batch_alter_table('producer_schedule_template_items', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('ix_prod_sched_item_day'))
        batch_op.drop_index(batch_op.f('ix_prod_sched_item_template'))
        batch_op.create_index(batch_op.f('ix_producer_schedule_template_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('producer_schedule_template_items_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('producer_schedule_templates', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('ix_prod_sched_tmpl_course'))
        batch_op.drop_index(batch_op.f('ix_prod_sched_tmpl_tenant'))
        batch_op.create_index(batch_op.f('ix_producer_schedule_templates_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('producer_schedule_templates_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.alter_column('context',
               existing_type=sa.VARCHAR(length=50),
               comment='practice | simulado | schedule | review | lesson',
               existing_nullable=False)
        batch_op.create_index('uq_attempt_non_simulado', ['user_id', 'question_id', 'context'], unique=True, postgresql_where=sa.text("context != 'simulado'"))
        batch_op.create_index('uq_attempt_simulado', ['user_id', 'question_id', 'simulado_attempt_id'], unique=True, postgresql_where=sa.text("context = 'simulado'"))

    with op.batch_alter_table('question_tags', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_question_tag', ['question_id', 'tag'])
        batch_op.drop_constraint(batch_op.f('question_tags_question_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=64), nullable=True, comment='ID externo para idempotência no bulk-import (hash do XLSX)'))
        batch_op.add_column(sa.Column('submitted_by_tenant_id', sa.UUID(as_uuid=False), nullable=True))
        batch_op.add_column(sa.Column('submitted_by_user_id', sa.UUID(as_uuid=False), nullable=True))
        batch_op.add_column(sa.Column('review_status', sa.Enum('approved', 'pending', 'rejected', name='review_status_enum'), nullable=False))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_user_id', sa.UUID(as_uuid=False), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('statement_hash', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('question_type', sa.Enum('interpretacao', 'aplicacao', 'raciocinio', 'memorizacao', name='question_type_enum'), nullable=True))
        batch_op.add_column(sa.Column('tip', sa.Text(), nullable=True, comment='Dica/macete gerado pelo Gemini'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('source_document_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_questions_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_questions_question_type'), ['question_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_statement_hash'), ['statement_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_submitted_by_tenant_id'), ['submitted_by_tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('questions_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['submitted_by_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['reviewed_by_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'tenants', ['submitted_by_tenant_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('settings')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('questions_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_questions_submitted_by_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_questions_statement_hash'))
        batch_op.drop_index(batch_op.f('ix_questions_review_status'))
        batch_op.drop_index(batch_op.f('ix_questions_question_type'))
        batch_op.drop_index(batch_op.f('ix_questions_external_id'))
        batch_op.alter_column('source_document_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('tip')
        batch_op.drop_column('question_type')
        batch_op.drop_column('statement_hash')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_user_id')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('review_status')
        batch_op.drop_column('submitted_by_user_id')
        batch_op.drop_column('submitted_by_tenant_id')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('question_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('question_tags_question_id_fkey'), 'questions', ['question_id'], ['id'])
        batch_op.drop_constraint('uq_question_tag', type_='unique')

    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.drop_index('uq_attempt_simulado', postgresql_where=sa.text("context = 'simulado'"))
        batch_op.drop_index('uq_attempt_non_simulado', postgresql_where=sa.text("context != 'simulado'"))
        batch_op.alter_column('context',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='practice | simulado | schedule | review | lesson',
               existing_nullable=False)

    with op.batch_alter_table('producer_schedule_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('producer_schedule_templates_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_producer_schedule_templates_tenant_id'))
        batch_op.create_index(batch_op.f('ix_prod_sched_tmpl_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prod_sched_tmpl_course'), ['course_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('producer_schedule_template_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('producer_schedule_template_items_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_producer_schedule_template_items_tenant_id'))
        batch_op.create_index(batch_op.f('ix_prod_sched_item_template'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prod_sched_item_day'), ['template_id', 'day_number'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('materials')

    with op.batch_alter_table('alternatives', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('alternatives_question_id_fkey'), 'questions', ['question_id'], ['id'])

    # ### end Alembic commands ###
